// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MUSH_Audio_Engine","status":true,"description":"[v.1.08] Implement the Mush Audio Engine features.","parameters":{"DevelopperMode":"true","GeneralFeatures":"","FEA_UIS":"true","FEA_VSC":"false","FEA_SPAPAN":"true","FEA_MAPAUTOPLAY":"false","VolumeBalance":"","VB_BGM":"100","VB_BGS":"100","VB_ME":"100","VB_SE":"100","VB_UIS":"100","VB_VSC":"100","SeUisVarFeatures":"","StaticFollowSe":"true","SeVarFeatures":"","SePitchVarFeature":"true","SePitchVarRange":"5","SeVolumeVarFeature":"true","SeVolumeVarRange":"3","UisVarFeatures":"","UisPitchVarFeature":"true","UisPitchVarRange":"5","UisVolumeVarFeature":"true","UisVolumeVarRange":"3","MenuOptions":"","MasterOptions":"","OptMasterFeature":"true","OptMasterText":"Master Volume","UisOptions":"","OptUisFeature":"true","OptUisText":"UIS Volume","VscOptions":"","OptVscFeature":"false","OptVscText":"VSC Volume"}},
{"name":"ItemReqForSkill","status":true,"description":"Item Requirement for Skill","parameters":{}},
{"name":"bunchastuff","status":true,"description":"","parameters":{}},
{"name":"WD_ItemUse","status":true,"description":"Creates a window that let the player select an item and returns the ID","parameters":{"itemSelector":"{\"selectorMode\":\"mode1\",\"includeEquip\":\"false\",\"metaTag\":\"69\"}","showDesc":"true","returnMode":"{\"returnMode\":\"mode1\",\"idVar\":\"70\",\"catVar\":\"71\",\"resultSwitch\":\"15\"}"}},
{"name":"TLB_LimitedShopStock","status":true,"description":"This plugin adds limited inventory to shops.","parameters":{"general":"","stockText":"(%1 left)","soldOutText":"(SOLD OUT)","defaultRestockTime":"-1","defaultRestockQuantity":"1","defaultStockMax":"99"}},
{"name":"FilterControllerMZ","status":true,"description":"FilterControllerMZ","parameters":{"decimalVariable":"true","displacementImage":"DisplacementMap","global-enable Settings":"","enabledAll-ShowInOptionMenu":"false","enabledAll-Text":"Filter Effects Enabled","enabledAll-DefaultValue":"true"}},
{"name":"WD_ConditionalChoice","status":true,"description":"Allow to input a check in the \"Show Choice\" that disables or hide the choice.","parameters":{"disabledSE":"","hiddenDefault":"hidden1","alternativeText":"[]","errorHandling":"error1"}},
{"name":"OrangeGreenworks","status":true,"description":"Steamworks Integration <OrangeGreenworks>","parameters":{}},
{"name":"Cyclone-Steam","status":true,"description":"Integrate your game with the Steamworks SDK - 1.00.01\n<pluginName:CycloneSteam>","parameters":{}}
];
